# Real educational seed content for the STEAM platform.
# Age groups: "13-15", "16-18", "18+", "all"

QUIZZES = [
    {
        "title": "Space & Our Solar System",
        "description": "Explore planets, moons and the basics of space science",
        "subject": "Science",
        "age_groups": ["13-15"],
        "questions": [
            {"question": "Which planet is closest to the Sun?", "options": ["Venus", "Mercury", "Earth", "Mars"], "correct_answer": "Mercury"},
            {"question": "What is the largest planet in our solar system?", "options": ["Saturn", "Neptune", "Jupiter", "Uranus"], "correct_answer": "Jupiter"},
            {"question": "Why is Mars called the Red Planet?", "options": ["It is very hot", "Iron oxide (rust) on its surface", "Its atmosphere is red", "It reflects sunlight"], "correct_answer": "Iron oxide (rust) on its surface"},
            {"question": "What force keeps the planets orbiting the Sun?", "options": ["Magnetism", "Friction", "Gravity", "Air pressure"], "correct_answer": "Gravity"},
            {"question": "How long does Earth take to orbit the Sun once?", "options": ["24 hours", "30 days", "365 days", "10 years"], "correct_answer": "365 days"},
        ],
    },
    {
        "title": "Cells & Chemistry Basics",
        "description": "Cell biology and foundational chemistry for high schoolers",
        "subject": "Science",
        "age_groups": ["16-18"],
        "questions": [
            {"question": "Which organelle is known as the powerhouse of the cell?", "options": ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], "correct_answer": "Mitochondria"},
            {"question": "What is the chemical symbol for gold?", "options": ["Go", "Gd", "Au", "Ag"], "correct_answer": "Au"},
            {"question": "A solution with pH 3 is:", "options": ["Strongly basic", "Neutral", "Acidic", "Slightly basic"], "correct_answer": "Acidic"},
            {"question": "What gas do plants absorb during photosynthesis?", "options": ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], "correct_answer": "Carbon dioxide"},
            {"question": "DNA is primarily found in which part of the cell?", "options": ["Cytoplasm", "Cell wall", "Nucleus", "Vacuole"], "correct_answer": "Nucleus"},
        ],
    },
    {
        "title": "Physics: Motion & Energy",
        "description": "Newtonian mechanics and energy concepts for college level",
        "subject": "Science",
        "age_groups": ["18+"],
        "questions": [
            {"question": "Newton's second law is expressed as:", "options": ["F = mv", "F = ma", "F = m/a", "F = a/m"], "correct_answer": "F = ma"},
            {"question": "The kinetic energy of a moving object is:", "options": ["mgh", "½mv²", "mv", "ma"], "correct_answer": "½mv²"},
            {"question": "The SI unit of power is the:", "options": ["Joule", "Newton", "Watt", "Pascal"], "correct_answer": "Watt"},
            {"question": "Approximate acceleration due to gravity on Earth:", "options": ["9.8 m/s²", "6.7 m/s²", "12.4 m/s²", "3.0 m/s²"], "correct_answer": "9.8 m/s²"},
            {"question": "Energy can be neither created nor destroyed — this is the law of:", "options": ["Entropy", "Conservation of energy", "Relativity", "Thermodynamic equilibrium"], "correct_answer": "Conservation of energy"},
        ],
    },
    {
        "title": "Computers & The Internet",
        "description": "How computers and the web actually work",
        "subject": "Technology",
        "age_groups": ["13-15"],
        "questions": [
            {"question": "What does CPU stand for?", "options": ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], "correct_answer": "Central Processing Unit"},
            {"question": "Who invented the World Wide Web?", "options": ["Bill Gates", "Steve Jobs", "Tim Berners-Lee", "Alan Turing"], "correct_answer": "Tim Berners-Lee"},
            {"question": "Computers store information using which number system?", "options": ["Decimal", "Binary", "Roman numerals", "Hexadecimal only"], "correct_answer": "Binary"},
            {"question": "Which of these is a web browser?", "options": ["Windows", "Firefox", "Linux", "Python"], "correct_answer": "Firefox"},
            {"question": "What does URL stand for?", "options": ["Uniform Resource Locator", "Universal Reading Link", "United Resource Library", "Uniform Routing Language"], "correct_answer": "Uniform Resource Locator"},
        ],
    },
    {
        "title": "Programming & Algorithms",
        "description": "Core programming logic and algorithmic thinking",
        "subject": "Technology",
        "age_groups": ["16-18", "18+"],
        "questions": [
            {"question": "An algorithm is best described as:", "options": ["A programming language", "A step-by-step procedure to solve a problem", "A type of computer", "A database"], "correct_answer": "A step-by-step procedure to solve a problem"},
            {"question": "What is the binary representation of the decimal number 5?", "options": ["100", "101", "110", "111"], "correct_answer": "101"},
            {"question": "Which structure repeats a block of code?", "options": ["Variable", "Loop", "Comment", "Constant"], "correct_answer": "Loop"},
            {"question": "The time complexity of binary search is:", "options": ["O(n)", "O(n²)", "O(log n)", "O(1)"], "correct_answer": "O(log n)"},
            {"question": "In Python, which keyword defines a function?", "options": ["func", "define", "def", "function"], "correct_answer": "def"},
        ],
    },
    {
        "title": "Forces & Structures",
        "description": "How engineers keep buildings and bridges standing",
        "subject": "Engineering",
        "age_groups": ["13-15", "16-18"],
        "questions": [
            {"question": "A bridge that supports weight through curved arches is a:", "options": ["Beam bridge", "Arch bridge", "Suspension bridge", "Truss bridge"], "correct_answer": "Arch bridge"},
            {"question": "The force that stretches a material is called:", "options": ["Compression", "Tension", "Torsion", "Shear"], "correct_answer": "Tension"},
            {"question": "Which shape is strongest for building structures?", "options": ["Square", "Circle", "Triangle", "Rectangle"], "correct_answer": "Triangle"},
            {"question": "A see-saw is an example of which simple machine?", "options": ["Pulley", "Lever", "Wedge", "Screw"], "correct_answer": "Lever"},
            {"question": "The Golden Gate Bridge is what type of bridge?", "options": ["Arch", "Beam", "Suspension", "Cantilever"], "correct_answer": "Suspension"},
        ],
    },
    {
        "title": "Engineering Materials & Design",
        "description": "Material properties and the engineering design process",
        "subject": "Engineering",
        "age_groups": ["16-18", "18+"],
        "questions": [
            {"question": "A material's resistance to being pulled apart is its:", "options": ["Hardness", "Tensile strength", "Density", "Conductivity"], "correct_answer": "Tensile strength"},
            {"question": "Steel is an alloy made mostly of:", "options": ["Iron and carbon", "Copper and zinc", "Aluminium and tin", "Nickel and chrome"], "correct_answer": "Iron and carbon"},
            {"question": "What does CAD stand for in engineering?", "options": ["Computer-Aided Design", "Central Analysis Diagram", "Circuit And Diode", "Calculated Area Drawing"], "correct_answer": "Computer-Aided Design"},
            {"question": "Why do engineers build prototypes?", "options": ["To sell them", "To test and improve a design before production", "For decoration", "To replace blueprints"], "correct_answer": "To test and improve a design before production"},
            {"question": "Concrete is strong in compression but weak in:", "options": ["Tension", "Heat", "Cold", "Sound"], "correct_answer": "Tension"},
        ],
    },
    {
        "title": "Color & Design Basics",
        "description": "Color theory and design principles every creator should know",
        "subject": "Arts",
        "age_groups": ["all"],
        "questions": [
            {"question": "Which are the three primary colors in traditional color theory?", "options": ["Red, green, blue", "Red, yellow, blue", "Cyan, magenta, yellow", "Orange, green, purple"], "correct_answer": "Red, yellow, blue"},
            {"question": "The complementary color of blue is:", "options": ["Green", "Red", "Orange", "Purple"], "correct_answer": "Orange"},
            {"question": "The golden ratio is approximately:", "options": ["3.14", "1.618", "2.718", "1.414"], "correct_answer": "1.618"},
            {"question": "Red, orange and yellow are considered:", "options": ["Cool colors", "Warm colors", "Neutral colors", "Pastel colors"], "correct_answer": "Warm colors"},
            {"question": "The 'rule of thirds' is used in:", "options": ["Cooking", "Composition of images", "Music tempo", "Sculpting"], "correct_answer": "Composition of images"},
        ],
    },
    {
        "title": "Algebra Foundations",
        "description": "Equations, order of operations and core algebra skills",
        "subject": "Mathematics",
        "age_groups": ["13-15"],
        "questions": [
            {"question": "Solve for x: 2x + 6 = 14", "options": ["2", "4", "6", "8"], "correct_answer": "4"},
            {"question": "What is (-3) × (-4)?", "options": ["-12", "12", "-7", "7"], "correct_answer": "12"},
            {"question": "Using order of operations: 3 + 4 × 2 = ?", "options": ["14", "11", "10", "24"], "correct_answer": "11"},
            {"question": "Expand: 3(x + 2)", "options": ["3x + 2", "3x + 6", "x + 6", "3x + 5"], "correct_answer": "3x + 6"},
            {"question": "What is the square root of 144?", "options": ["10", "11", "12", "14"], "correct_answer": "12"},
        ],
    },
    {
        "title": "Geometry & Trigonometry",
        "description": "Angles, triangles and trigonometric ratios",
        "subject": "Mathematics",
        "age_groups": ["16-18"],
        "questions": [
            {"question": "The sum of interior angles in a triangle is:", "options": ["90°", "180°", "270°", "360°"], "correct_answer": "180°"},
            {"question": "A right triangle has legs 3 and 4. The hypotenuse is:", "options": ["5", "6", "7", "12"], "correct_answer": "5"},
            {"question": "sin(30°) equals:", "options": ["1", "0.5", "0.866", "0"], "correct_answer": "0.5"},
            {"question": "The area of a circle with radius r is:", "options": ["2πr", "πr²", "πd", "r²"], "correct_answer": "πr²"},
            {"question": "180° in radians is:", "options": ["π/2", "π", "2π", "π/4"], "correct_answer": "π"},
        ],
    },
    {
        "title": "Calculus & Probability",
        "description": "Derivatives, integrals and probability for college level",
        "subject": "Mathematics",
        "age_groups": ["18+"],
        "questions": [
            {"question": "The derivative of x² is:", "options": ["x", "2x", "x²/2", "2"], "correct_answer": "2x"},
            {"question": "The derivative of sin(x) is:", "options": ["-sin(x)", "cos(x)", "-cos(x)", "tan(x)"], "correct_answer": "cos(x)"},
            {"question": "An integral computes the:", "options": ["Slope of a curve", "Area under a curve", "Maximum value", "Rate of change"], "correct_answer": "Area under a curve"},
            {"question": "Probability of getting two heads in two fair coin flips:", "options": ["1/2", "1/3", "1/4", "3/4"], "correct_answer": "1/4"},
            {"question": "The limit of (1 + 1/n)ⁿ as n → ∞ is:", "options": ["1", "π", "e", "∞"], "correct_answer": "e"},
        ],
    },
    # Diagnostic quiz: every tagged wrong option maps to a known misconception
    # (see MISCONCEPTIONS below). Untagged wrong options are plain errors.
    {
        "title": "Forces & Motion: Misconception Check",
        "description": "Find out which force-and-motion ideas are tripping you up",
        "subject": "Science",
        "age_groups": ["13-15", "16-18"],
        "diagnostic": True,
        "questions": [
            {
                "question": "A hockey puck slides across frictionless ice after being hit. Which horizontal forces act on it while it slides?",
                "options": ["No horizontal force", "The force of the hit, slowly running out", "A forward force that keeps it moving", "A force that grows as the puck speeds up"],
                "correct_answer": "No horizontal force",
                "misconceptions": {
                    "The force of the hit, slowly running out": "impetus",
                    "A forward force that keeps it moving": "motion-implies-force",
                    "A force that grows as the puck speeds up": "force-proportional-to-velocity",
                },
            },
            {
                "question": "A 1 kg ball and a 5 kg ball of the same size are dropped together from 2 m. Air resistance is negligible. Which lands first?",
                "options": ["They land at the same time", "The 5 kg ball", "The 1 kg ball"],
                "correct_answer": "They land at the same time",
                "misconceptions": {"The 5 kg ball": "heavier-falls-faster"},
            },
            {
                "question": "A truck hits a small car head-on. During the collision, how does the force of the car on the truck compare to the force of the truck on the car?",
                "options": ["Equal in size", "Smaller, because the car has less mass", "Zero, because the car is the one being hit", "Larger, because the car gets damaged more"],
                "correct_answer": "Equal in size",
                "misconceptions": {
                    "Smaller, because the car has less mass": "greater-mass-greater-force",
                    "Zero, because the car is the one being hit": "only-active-objects-push",
                    "Larger, because the car gets damaged more": "damage-shows-force",
                },
            },
            {
                "question": "A ball is thrown straight up. At its highest point, what is the net force on it?",
                "options": ["Its weight, pointing down", "Zero", "An upward force from the throw, equal to its weight"],
                "correct_answer": "Its weight, pointing down",
                "misconceptions": {
                    "Zero": "zero-velocity-zero-force",
                    "An upward force from the throw, equal to its weight": "impetus",
                },
            },
            {
                "question": "A box is pushed across a rough floor at constant speed. How does the pushing force compare to friction?",
                "options": ["Equal to friction", "Greater than friction", "Less than friction"],
                "correct_answer": "Equal to friction",
                "misconceptions": {"Greater than friction": "motion-implies-force"},
            },
            {
                "question": "Astronauts float inside a space station orbiting about 400 km above Earth. Why?",
                "options": ["They and the station are falling around Earth together", "There is no gravity in space", "There is no air to push them down", "The station's engines cancel gravity"],
                "correct_answer": "They and the station are falling around Earth together",
                "misconceptions": {
                    "There is no gravity in space": "no-gravity-in-space",
                    "There is no air to push them down": "gravity-needs-air",
                },
            },
            {
                "question": "Compared to on Earth, an astronaut's mass on the Moon is:",
                "options": ["The same", "About one sixth", "Zero"],
                "correct_answer": "The same",
                "misconceptions": {"About one sixth": "mass-weight-confusion", "Zero": "mass-weight-confusion"},
            },
            {
                "question": "A ball rolls horizontally off the edge of a table. Ignoring air, what path does it follow?",
                "options": ["A curve that bends downward right from the edge", "Straight out, then straight down", "Straight out for a while, then a curve down"],
                "correct_answer": "A curve that bends downward right from the edge",
                "misconceptions": {
                    "Straight out, then straight down": "impetus",
                    "Straight out for a while, then a curve down": "impetus",
                },
            },
        ],
    },
]

# Misconception catalogue used by diagnostic quizzes and the Debug Arena.
# Science categories follow the force-and-motion misconception taxonomy
# published with the Force Concept Inventory (Hestenes, Wells & Swackhamer,
# The Physics Teacher, 1992) plus common mass/weight and gravity
# misconceptions. The other areas list widely reported classroom
# misconceptions. Questions and scenarios in this file are original.
MISCONCEPTIONS = {
    "impetus": {"subject": "Science", "description": "Thinks an object carries a stored 'force of the push' that keeps it moving and runs out"},
    "motion-implies-force": {"subject": "Science", "description": "Thinks constant motion needs a net force in the direction of motion"},
    "force-proportional-to-velocity": {"subject": "Science", "description": "Thinks force sets speed rather than acceleration"},
    "heavier-falls-faster": {"subject": "Science", "description": "Thinks heavier objects fall faster without air resistance"},
    "greater-mass-greater-force": {"subject": "Science", "description": "Thinks the heavier object exerts a larger force in an interaction"},
    "only-active-objects-push": {"subject": "Science", "description": "Thinks only the 'active' object in a collision exerts a force"},
    "damage-shows-force": {"subject": "Science", "description": "Judges force size by damage instead of Newton's third law"},
    "zero-velocity-zero-force": {"subject": "Science", "description": "Thinks a momentarily stopped object has no net force"},
    "no-gravity-in-space": {"subject": "Science", "description": "Thinks gravity disappears in orbit"},
    "gravity-needs-air": {"subject": "Science", "description": "Thinks gravity depends on air or air pressure"},
    "mass-weight-confusion": {"subject": "Science", "description": "Confuses mass with weight"},
    "assignment-links-variables": {"subject": "Technology", "description": "Thinks b = a ties the two variables together, so later changes to a also change b"},
    "bits-bytes-confusion": {"subject": "Technology", "description": "Treats megabits (Mb) and megabytes (MB) as the same unit"},
    "current-consumed": {"subject": "Engineering", "description": "Thinks components use up electric current, so less flows further along a series circuit"},
    "machines-reduce-work": {"subject": "Engineering", "description": "Thinks simple machines reduce the work needed rather than trading force for distance"},
    "style-from-single-feature": {"subject": "Arts", "description": "Assigns an artwork to a movement from one surface feature instead of its overall approach"},
    "additive-subtractive-mixing": {"subject": "Arts", "description": "Expects paint to mix like light, not seeing that pigments mix subtractively"},
    "add-numerators-and-denominators": {"subject": "Mathematics", "description": "Adds fractions by adding numerators and denominators separately"},
    "percent-change-symmetric": {"subject": "Mathematics", "description": "Thinks a p% increase followed by a p% decrease returns to the starting value"},
}

# Debug Arena: each scenario is a worked solution with exactly one flawed step
# (the first place the reasoning goes wrong). Students find that step and name
# the concept it breaks. flawed_step, correct_explanation, misconception and
# debrief stay on the server until the student submits.
ARENA_CHALLENGES = [
    {
        "title": "The Top of the Throw",
        "subject": "Science",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "A 0.5 kg ball is thrown straight up. Ignoring air resistance, what is the net force on the ball at its highest point? (g = 9.8 m/s²)",
        "steps": [
            "Once the ball leaves the hand, the only force acting on it is gravity.",
            "On the way up, gravity slows the ball down by 9.8 m/s every second.",
            "At the highest point the ball stops rising for an instant, so its velocity is 0 m/s.",
            "Since the velocity is zero, the net force on the ball at that instant must also be zero.",
            "So the net force at the top is 0 N.",
        ],
        "explanations": [
            "Zero velocity does not mean zero force: gravity still pulls down, so the net force is the ball's weight.",
            "Gravity switches off for an instant at the top of the path.",
            "The force of the throw is still pushing up at the top and cancels gravity.",
        ],
        "flawed_step": 3,
        "correct_explanation": "Zero velocity does not mean zero force: gravity still pulls down, so the net force is the ball's weight.",
        "misconception": "zero-velocity-zero-force",
        "debrief": "Velocity and force are different things. At the top the ball's velocity is zero for an instant, but gravity never stops acting: net force = mg = 0.5 × 9.8 = 4.9 N downward. That is why the ball immediately starts falling — its velocity keeps changing even at the moment it is zero.",
    },
    {
        "title": "An Astronaut on the Moon",
        "subject": "Science",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "An astronaut has a mass of 60 kg on Earth. What are her mass and weight on the Moon? (g on Earth = 9.8 m/s², g on the Moon ≈ 1.6 m/s²)",
        "steps": [
            "On Earth her weight is W = m × g = 60 × 9.8 = 588 N.",
            "The Moon's gravity is about one sixth of Earth's (1.6 ÷ 9.8 ≈ 0.16).",
            "Since gravity is about six times weaker, her mass on the Moon is 60 ÷ 6 = 10 kg.",
            "Her weight on the Moon is W = m × g = 10 × 1.6 = 16 N.",
        ],
        "explanations": [
            "Mass is the amount of matter and does not change with location; only weight depends on gravity.",
            "The Moon's gravity is actually stronger than Earth's.",
            "Weight should be found by dividing mass by g, not multiplying.",
        ],
        "flawed_step": 2,
        "correct_explanation": "Mass is the amount of matter and does not change with location; only weight depends on gravity.",
        "misconception": "mass-weight-confusion",
        "debrief": "Mass measures how much matter (and inertia) an object has, so it is 60 kg everywhere. Weight is the pull of gravity on that mass: on the Moon W = 60 × 1.6 ≈ 96 N, about one sixth of her 588 N weight on Earth.",
    },
    {
        "title": "Tracing Variables",
        "subject": "Technology",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "What does this program print?\n\na = 5\nb = a\na = 7\nprint(b)",
        "steps": [
            "a = 5 stores the value 5 in a.",
            "b = a gives b the value of a, which is 5.",
            "a = 7 changes a to 7. Because b was set equal to a, b changes to 7 as well.",
            "print(b) therefore prints 7.",
        ],
        "explanations": [
            "Assignment copies the value at that moment; changing a later does not change b.",
            "print(b) prints the name of the variable, not its value.",
            "The program crashes because a is assigned twice.",
        ],
        "flawed_step": 2,
        "correct_explanation": "Assignment copies the value at that moment; changing a later does not change b.",
        "misconception": "assignment-links-variables",
        "debrief": "b = a copies the value a holds right then (5). Giving a a new value afterwards does not reach back and change b, so the program prints 5. (Two names that share one mutable object, such as a list, behave differently — but here we only reassign a number.)",
    },
    {
        "title": "How Long Is the Download?",
        "subject": "Technology",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "Your internet plan is 100 Mbps. Ignoring overhead, how long does it take to download a 600 MB game update?",
        "steps": [
            "The file is 600 MB (megabytes) and the connection speed is 100 Mbps.",
            "100 Mbps means 100 megabytes per second.",
            "Time = 600 MB ÷ 100 MB/s = 6 seconds.",
        ],
        "explanations": [
            "Mbps counts megabits, and 1 byte is 8 bits, so 100 Mbps is only 12.5 MB/s.",
            "The speed should be multiplied by the file size, not divided into it.",
            "1 MB is 1024 Mb, so the connection is much faster than stated.",
        ],
        "flawed_step": 1,
        "correct_explanation": "Mbps counts megabits, and 1 byte is 8 bits, so 100 Mbps is only 12.5 MB/s.",
        "misconception": "bits-bytes-confusion",
        "debrief": "A lowercase b means bits and an uppercase B means bytes; 1 byte = 8 bits. 100 Mbps ÷ 8 = 12.5 MB/s, so the update takes about 600 ÷ 12.5 = 48 seconds in ideal conditions — eight times longer than the flawed answer.",
    },
    {
        "title": "Two Bulbs in Series",
        "subject": "Engineering",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "A battery is connected to two identical bulbs in series (one after the other in a single loop). How does the brightness of the two bulbs compare?",
        "steps": [
            "In a series circuit there is only one path, so the charge flows through bulb A and then bulb B.",
            "Bulb A uses up part of the current to make light, so less current is left for bulb B.",
            "So bulb B glows more dimly than bulb A.",
        ],
        "explanations": [
            "Current is not used up: the same current flows through every part of a series loop. Bulbs transfer energy, not charge.",
            "Bulb B is dimmer because it is farther from the battery.",
            "Identical bulbs always have different resistances when connected in series.",
        ],
        "flawed_step": 1,
        "correct_explanation": "Current is not used up: the same current flows through every part of a series loop. Bulbs transfer energy, not charge.",
        "misconception": "current-consumed",
        "debrief": "Charge is conserved, so the current is the same everywhere in a single loop. What the bulbs take is energy carried by the charges, which shows up as a voltage drop across each bulb. Identical bulbs get the same current and the same share of the voltage, so they glow equally brightly.",
    },
    {
        "title": "Does a Lever Save Work?",
        "subject": "Engineering",
        "age_groups": ["all"],
        "time_limit_seconds": 120,
        "problem": "Using a lever, you lift a 200 N rock by 0.1 m while pushing down with only 50 N. How much work do you do? (Assume an ideal, frictionless lever.)",
        "steps": [
            "Work done lifting the rock = force × distance = 200 N × 0.1 m = 20 J.",
            "The lever lets you push with 50 N, which is 4 times less than the rock's weight.",
            "Because your force is 4 times smaller, the work you do is also 4 times smaller: 20 J ÷ 4 = 5 J.",
            "So the lever saves you 15 J of work.",
        ],
        "explanations": [
            "A lever trades force for distance: you push with a quarter of the force over four times the distance (0.4 m), so the work is still 20 J.",
            "The work on the rock should be 200 N ÷ 0.1 m, not 200 N × 0.1 m.",
            "A lever increases the work needed because the bar adds extra length.",
        ],
        "flawed_step": 2,
        "correct_explanation": "A lever trades force for distance: you push with a quarter of the force over four times the distance (0.4 m), so the work is still 20 J.",
        "misconception": "machines-reduce-work",
        "debrief": "Simple machines reduce the force you need, not the work. With a 4:1 lever you push 50 N through 0.4 m: 50 × 0.4 = 20 J, the same as lifting the rock directly. A real lever loses a little to friction, so the work you do is slightly more than 20 J — never less.",
    },
    {
        "title": "Classifying The Starry Night",
        "subject": "Arts",
        "age_groups": ["all"],
        "time_limit_seconds": 120,
        "problem": "Which art movement does Vincent van Gogh's painting The Starry Night (1889) belong to?",
        "steps": [
            "The Starry Night was painted by Vincent van Gogh in June 1889, while he was staying at the asylum in Saint-Rémy-de-Provence, France.",
            "It shows a swirling night sky over a small village, with a tall cypress tree in the foreground.",
            "The paint is applied in thick, clearly visible brushstrokes.",
            "Visible brushstrokes are the defining mark of Impressionism, so The Starry Night is an Impressionist painting.",
        ],
        "explanations": [
            "A movement can't be identified from one surface feature. Van Gogh was a Post-Impressionist who used colour and swirling forms to express feeling rather than to record a moment of natural light.",
            "The painting is Cubist because the stars are drawn as geometric shapes.",
            "It belongs to the Renaissance because it is an oil painting on canvas.",
        ],
        "flawed_step": 3,
        "correct_explanation": "A movement can't be identified from one surface feature. Van Gogh was a Post-Impressionist who used colour and swirling forms to express feeling rather than to record a moment of natural light.",
        "misconception": "style-from-single-feature",
        "debrief": "Visible brushwork appears in many styles, so on its own it proves little. Impressionists such as Claude Monet used quick strokes to capture changing natural light as they observed it. Van Gogh, a Post-Impressionist, pushed colour and line to express emotion: The Starry Night combines the view from his window with memory and imagination, and its swirling sky is not something anyone could actually see.",
    },
    {
        "title": "Mixing Red, Green and Blue Paint",
        "subject": "Arts",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "A student mixes equal amounts of red, green and blue paint. What colour will they get?",
        "steps": [
            "On a screen, red, green and blue light at full strength combine to make white.",
            "Paint follows the same colour-mixing rules as light, so red, green and blue paint also make white.",
            "The student will get white paint.",
        ],
        "explanations": [
            "Light mixes additively, but pigments mix subtractively: each pigment absorbs more light, so the mixture gets darker, not whiter.",
            "Screens actually use red, yellow and blue as their primaries.",
            "The result depends only on which paint is added first.",
        ],
        "flawed_step": 1,
        "correct_explanation": "Light mixes additively, but pigments mix subtractively: each pigment absorbs more light, so the mixture gets darker, not whiter.",
        "misconception": "additive-subtractive-mixing",
        "debrief": "Coloured lights add together, so red, green and blue light reach your eye as white. Paint works the other way: each pigment absorbs (subtracts) part of the light, so mixing more pigments reflects less of it. Red, green and blue paint give a dark, muddy brown. That is why painters and printers use different primaries (such as cyan, magenta and yellow).",
    },
    {
        "title": "Adding Fractions in a Recipe",
        "subject": "Mathematics",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "A recipe uses 1/2 cup of milk and 1/3 cup of water. How much liquid is that in total?",
        "steps": [
            "To add fractions, add the numerators and add the denominators: 1/2 + 1/3 = (1 + 1)/(2 + 3).",
            "That gives 2/5.",
            "So the recipe uses 2/5 of a cup of liquid in total.",
        ],
        "explanations": [
            "Fractions need a common denominator before adding: 1/2 + 1/3 = 3/6 + 2/6 = 5/6.",
            "The fractions should be multiplied instead: 1/2 × 1/3 = 1/6.",
            "The smaller fraction should be subtracted from the larger one.",
        ],
        "flawed_step": 0,
        "correct_explanation": "Fractions need a common denominator before adding: 1/2 + 1/3 = 3/6 + 2/6 = 5/6.",
        "misconception": "add-numerators-and-denominators",
        "debrief": "2/5 is less than 1/2, so the total would be smaller than one of its parts. The denominator names the size of the pieces, and you can only add pieces of the same size: 1/2 = 3/6 and 1/3 = 2/6, which gives 5/6 of a cup.",
    },
    {
        "title": "Price Up, Then on Sale",
        "subject": "Mathematics",
        "age_groups": ["all"],
        "time_limit_seconds": 90,
        "problem": "A jacket costs $100. The shop raises the price by 20%, then a week later puts it on sale at 20% off. What is the final price?",
        "steps": [
            "After a 20% increase the price is 100 × 1.20 = $120.",
            "A 20% increase followed by a 20% decrease cancel out, because the percentages are the same.",
            "So the final price is back to $100.",
        ],
        "explanations": [
            "The 20% discount is taken from the new price of $120, so it removes $24, not $20: 120 × 0.80 = $96.",
            "A percentage can't be applied twice to the same item.",
            "The increase should be 100 + 20% = $100.20.",
        ],
        "flawed_step": 1,
        "correct_explanation": "The 20% discount is taken from the new price of $120, so it removes $24, not $20: 120 × 0.80 = $96.",
        "misconception": "percent-change-symmetric",
        "debrief": "Each percentage is applied to the current price. 20% of $120 is $24, so the sale price is $96. In general, a p% rise then a p% cut multiplies the price by (1 + p)(1 − p) = 1 − p², which is always less than 1.",
    },
]

ACTIVITIES = [
    {
        "title": "Solar System Matching",
        "description": "Match planets with their characteristics",
        "type": "matching",
        "difficulty": "Easy",
        "subject": "Science",
        "age_groups": ["13-15"],
        "content": {
            "items": [
                {"id": "mercury", "text": "Mercury", "match": "closest-to-sun"},
                {"id": "earth", "text": "Earth", "match": "has-life"},
                {"id": "jupiter", "text": "Jupiter", "match": "largest-planet"},
                {"id": "mars", "text": "Mars", "match": "red-planet"},
            ],
            "matches": [
                {"id": "closest-to-sun", "text": "Closest to the Sun"},
                {"id": "has-life", "text": "Has life"},
                {"id": "largest-planet", "text": "Largest planet"},
                {"id": "red-planet", "text": "The Red Planet"},
            ],
        },
    },
    {
        "title": "Lab Equipment Matching",
        "description": "Match laboratory tools with what they are used for",
        "type": "matching",
        "difficulty": "Medium",
        "subject": "Science",
        "age_groups": ["16-18"],
        "content": {
            "items": [
                {"id": "beaker", "text": "Beaker", "match": "hold-liquids"},
                {"id": "microscope", "text": "Microscope", "match": "magnify"},
                {"id": "bunsen", "text": "Bunsen burner", "match": "heat"},
                {"id": "pipette", "text": "Pipette", "match": "measure-drops"},
            ],
            "matches": [
                {"id": "hold-liquids", "text": "Holding and mixing liquids"},
                {"id": "magnify", "text": "Magnifying tiny objects"},
                {"id": "heat", "text": "Heating substances"},
                {"id": "measure-drops", "text": "Transferring precise liquid volumes"},
            ],
        },
    },
    {
        "title": "Element Symbols",
        "description": "Match chemical elements with their periodic table symbols",
        "type": "matching",
        "difficulty": "Medium",
        "subject": "Science",
        "age_groups": ["16-18", "18+"],
        "content": {
            "items": [
                {"id": "gold", "text": "Gold", "match": "au"},
                {"id": "sodium", "text": "Sodium", "match": "na"},
                {"id": "iron", "text": "Iron", "match": "fe"},
                {"id": "oxygen", "text": "Oxygen", "match": "o"},
            ],
            "matches": [
                {"id": "au", "text": "Au"},
                {"id": "na", "text": "Na"},
                {"id": "fe", "text": "Fe"},
                {"id": "o", "text": "O"},
            ],
        },
    },
    {
        "title": "Tech Terms Matching",
        "description": "Match computing terms with their meanings",
        "type": "matching",
        "difficulty": "Easy",
        "subject": "Technology",
        "age_groups": ["13-15"],
        "content": {
            "items": [
                {"id": "cpu", "text": "CPU", "match": "brain"},
                {"id": "ram", "text": "RAM", "match": "short-memory"},
                {"id": "html", "text": "HTML", "match": "webpage"},
                {"id": "wifi", "text": "Wi-Fi", "match": "wireless"},
            ],
            "matches": [
                {"id": "brain", "text": "The 'brain' of the computer"},
                {"id": "short-memory", "text": "Short-term working memory"},
                {"id": "webpage", "text": "Language for building web pages"},
                {"id": "wireless", "text": "Wireless internet connection"},
            ],
        },
    },
    {
        "title": "Programming Concepts",
        "description": "Match programming concepts with their definitions",
        "type": "matching",
        "difficulty": "Medium",
        "subject": "Technology",
        "age_groups": ["16-18", "18+"],
        "content": {
            "items": [
                {"id": "loop", "text": "Loop", "match": "repeat"},
                {"id": "variable", "text": "Variable", "match": "store"},
                {"id": "function", "text": "Function", "match": "reusable"},
                {"id": "bug", "text": "Bug", "match": "error"},
            ],
            "matches": [
                {"id": "repeat", "text": "Repeats a block of code"},
                {"id": "store", "text": "Stores a value with a name"},
                {"id": "reusable", "text": "Reusable block of code"},
                {"id": "error", "text": "An error in a program"},
            ],
        },
    },
    {
        "title": "Simple Machines",
        "description": "Match simple machines with everyday examples",
        "type": "matching",
        "difficulty": "Easy",
        "subject": "Engineering",
        "age_groups": ["13-15"],
        "content": {
            "items": [
                {"id": "lever", "text": "Lever", "match": "seesaw"},
                {"id": "pulley", "text": "Pulley", "match": "flagpole"},
                {"id": "inclined", "text": "Inclined plane", "match": "ramp"},
                {"id": "wheel", "text": "Wheel & axle", "match": "doorknob"},
            ],
            "matches": [
                {"id": "seesaw", "text": "A see-saw"},
                {"id": "flagpole", "text": "Raising a flag up a pole"},
                {"id": "ramp", "text": "A wheelchair ramp"},
                {"id": "doorknob", "text": "A doorknob"},
            ],
        },
    },
    {
        "title": "Bridge Types",
        "description": "Match bridge types with how they carry loads",
        "type": "matching",
        "difficulty": "Medium",
        "subject": "Engineering",
        "age_groups": ["16-18"],
        "content": {
            "items": [
                {"id": "arch", "text": "Arch bridge", "match": "compression"},
                {"id": "suspension", "text": "Suspension bridge", "match": "cables"},
                {"id": "beam", "text": "Beam bridge", "match": "simple-span"},
                {"id": "truss", "text": "Truss bridge", "match": "triangles"},
            ],
            "matches": [
                {"id": "compression", "text": "Carries load through curved compression"},
                {"id": "cables", "text": "Hangs the deck from main cables"},
                {"id": "simple-span", "text": "Simple horizontal span on supports"},
                {"id": "triangles", "text": "Network of triangles spreads the load"},
            ],
        },
    },
    {
        "title": "Art Movements",
        "description": "Match famous art movements with their iconic artists",
        "type": "matching",
        "difficulty": "Medium",
        "subject": "Arts",
        "age_groups": ["16-18", "18+"],
        "content": {
            "items": [
                {"id": "impressionism", "text": "Impressionism", "match": "monet"},
                {"id": "cubism", "text": "Cubism", "match": "picasso"},
                {"id": "surrealism", "text": "Surrealism", "match": "dali"},
                {"id": "popart", "text": "Pop Art", "match": "warhol"},
            ],
            "matches": [
                {"id": "monet", "text": "Claude Monet"},
                {"id": "picasso", "text": "Pablo Picasso"},
                {"id": "dali", "text": "Salvador Dalí"},
                {"id": "warhol", "text": "Andy Warhol"},
            ],
        },
    },
    {
        "title": "Math Operations",
        "description": "Match equations with their results",
        "type": "matching",
        "difficulty": "Easy",
        "subject": "Mathematics",
        "age_groups": ["13-15"],
        "content": {
            "items": [
                {"id": "eq1", "text": "15 + 27", "match": "result1"},
                {"id": "eq2", "text": "8 × 9", "match": "result2"},
                {"id": "eq3", "text": "100 ÷ 4", "match": "result3"},
                {"id": "eq4", "text": "7²", "match": "result4"},
            ],
            "matches": [
                {"id": "result1", "text": "42"},
                {"id": "result2", "text": "72"},
                {"id": "result3", "text": "25"},
                {"id": "result4", "text": "49"},
            ],
        },
    },
    {
        "title": "Derivative Matching",
        "description": "Match functions with their derivatives",
        "type": "matching",
        "difficulty": "Hard",
        "subject": "Mathematics",
        "age_groups": ["18+"],
        "content": {
            "items": [
                {"id": "x2", "text": "x²", "match": "d-2x"},
                {"id": "sinx", "text": "sin(x)", "match": "d-cosx"},
                {"id": "ex", "text": "eˣ", "match": "d-ex"},
                {"id": "lnx", "text": "ln(x)", "match": "d-1x"},
            ],
            "matches": [
                {"id": "d-2x", "text": "2x"},
                {"id": "d-cosx", "text": "cos(x)"},
                {"id": "d-ex", "text": "eˣ"},
                {"id": "d-1x", "text": "1/x"},
            ],
        },
    },
]

CONTENT_ITEMS = [
    # ------------------ SCIENCE ------------------
    {
        "title": "Why Is the Sky Blue? The Physics of Light Scattering",
        "type": "article",
        "subject": "Science",
        "age_groups": ["13-15"],
        "difficulty": "Easy",
        "read_time": "5 min",
        "summary": "Sunlight looks white, but it is actually a mix of every color. The sky is blue because of how those colors bounce off air molecules — a process called Rayleigh scattering.",
        "body": "Sunlight is a mixture of all the colors of the rainbow. Each color travels as a wave, and each wave has a different length: red light has long waves, while blue and violet light have short waves.\n\nWhen sunlight enters Earth's atmosphere, it crashes into tiny gas molecules like nitrogen and oxygen. Short waves get bounced around (scattered) much more than long waves — about 4 times more for blue than for red. This bouncing is called Rayleigh scattering, named after the British physicist Lord Rayleigh who explained it in the 1870s.\n\nBecause blue light scatters in every direction across the whole sky, wherever you look up, blue light reaches your eyes. Violet light actually scatters even more, but our eyes are less sensitive to violet, and some of it is absorbed high in the atmosphere — so the sky appears blue, not purple.\n\nAt sunset, sunlight travels through much more atmosphere to reach you. Nearly all the blue gets scattered away before the light arrives, leaving the long red and orange waves — which is why sunsets glow red. The same physics explains why the sky on Mars looks butterscotch during the day and blue at sunset: its dusty atmosphere scatters light differently.",
        "external_url": "https://spaceplace.nasa.gov/blue-sky/en/",
        "external_label": "NASA Space Place",
    },
    {
        "title": "How Vaccines Train Your Immune System",
        "type": "article",
        "subject": "Science",
        "age_groups": ["16-18"],
        "difficulty": "Medium",
        "read_time": "7 min",
        "summary": "Vaccines work like a training exercise for your immune system: they show your body a harmless preview of a pathogen so it can build memory cells ready to fight the real thing.",
        "body": "Your immune system has two lines of defense. The innate system responds instantly but generically — think fever and inflammation. The adaptive system is slower but precise: white blood cells called B-cells produce antibodies shaped to lock onto one specific invader, while T-cells destroy infected cells.\n\nThe first time your body meets a new pathogen, building this precise response takes one to two weeks — often long enough for you to get seriously ill. But afterwards, your body keeps memory B-cells and memory T-cells that remember the invader for years.\n\nVaccines exploit this memory. They present your immune system with a harmless version of the threat: a weakened virus (measles vaccine), an inactivated one (polio shot), a single protein from its surface (hepatitis B), or — in mRNA vaccines — genetic instructions that let your own cells briefly produce that protein. Your immune system mounts a full training response and stores the memory, without you ever being in danger.\n\nWhen the real pathogen shows up, your body recognizes it immediately and neutralizes it before it can multiply. Herd immunity extends this protection: when enough people are immune, outbreaks can't find new hosts, protecting even those who can't be vaccinated. Vaccines are estimated by the WHO to prevent 3.5 to 5 million deaths every year.",
        "external_url": "https://www.who.int/news-room/feature-stories/detail/how-do-vaccines-work",
        "external_label": "World Health Organization",
    },
    {
        "title": "CRISPR: Editing the Code of Life",
        "type": "article",
        "subject": "Science",
        "age_groups": ["18+"],
        "difficulty": "Hard",
        "read_time": "9 min",
        "summary": "CRISPR-Cas9 is a molecular 'find and replace' tool that lets scientists edit DNA with unprecedented precision — borrowed from a defense system bacteria use against viruses.",
        "body": "In the 1980s, scientists noticed strange repeating sequences in bacterial DNA — Clustered Regularly Interspaced Short Palindromic Repeats, or CRISPR. Between the repeats sat fragments of viral DNA: a genetic 'most wanted' list. Bacteria, it turned out, keep records of viruses that attacked them, and use a protein called Cas9 as a guided missile to slice up any matching DNA that invades again.\n\nIn 2012, Jennifer Doudna and Emmanuelle Charpentier showed this system could be reprogrammed. By giving Cas9 a custom 'guide RNA', researchers can direct it to cut virtually any 20-letter DNA sequence in any organism. The cell then repairs the cut — and scientists can exploit that repair to disable a gene or paste in a corrected version. The discovery won the 2020 Nobel Prize in Chemistry.\n\nThe applications are enormous. In 2023, regulators approved Casgevy, the first CRISPR therapy, which cures sickle cell disease by editing a patient's own blood stem cells. Trials are underway for certain cancers, hereditary blindness, and high cholesterol. In agriculture, CRISPR has produced disease-resistant wheat and non-browning mushrooms.\n\nThe technology also raises hard ethical questions. Edits to embryos would be inherited by future generations, and in 2018 a Chinese scientist was jailed for creating the first gene-edited babies. The scientific consensus today: editing to cure disease in a consenting patient is medicine; editing traits in future humans crosses a line we are not ready for.",
        "external_url": "https://www.genome.gov/about-genomics/policy-issues/what-is-genome-editing",
        "external_label": "National Human Genome Research Institute",
    },
    {
        "title": "Extract DNA from a Strawberry",
        "type": "experiment",
        "subject": "Science",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Easy",
        "duration": "30 min",
        "materials": ["1 ripe strawberry", "Zip-lock bag", "Dish soap (1 tsp)", "Salt (½ tsp)", "Water (½ cup)", "Cold rubbing alcohol", "Coffee filter", "Clear glass"],
        "summary": "Strawberries have eight copies of every chromosome, which makes them perfect for extracting visible strands of real DNA in your kitchen.",
        "body": "Every living cell carries DNA, but you normally need a lab to see it. Strawberries are the exception: they are octoploid (8 copies of each chromosome) and soft enough to mash by hand.\n\nStep 1 — Mash: Put the strawberry in the zip-lock bag, seal it, and crush it thoroughly for 2 minutes.\n\nStep 2 — Lyse: Mix the water, dish soap and salt, pour into the bag, and gently mash for 1 more minute. The soap dissolves the fatty membranes around each cell and its nucleus, spilling DNA into the liquid. The salt helps DNA strands clump together.\n\nStep 3 — Filter: Pour the mixture through a coffee filter into a clear glass so only the pink liquid passes through.\n\nStep 4 — Precipitate: Slowly pour very cold rubbing alcohol down the side of the glass to form a layer on top. DNA is not soluble in alcohol — within a minute you will see white, stringy strands rising into the alcohol layer. That's real DNA, and you can lift it out with a toothpick.\n\nThe same chemistry — lyse, filter, precipitate — is how forensic labs and COVID test facilities begin processing genetic samples.",
        "external_url": "https://www.sciencebuddies.org/stem-activities/strawberry-dna",
        "external_label": "Science Buddies",
    },
    {
        "title": "Build a Lemon Battery",
        "type": "experiment",
        "subject": "Science",
        "age_groups": ["13-15"],
        "difficulty": "Easy",
        "duration": "45 min",
        "materials": ["2-4 lemons", "Copper coins or copper strips", "Galvanized (zinc) nails", "Alligator clip wires", "Small LED"],
        "summary": "Turn lemons into a working battery and discover the electrochemistry that powers everything from your phone to electric cars.",
        "body": "A battery is just two different metals separated by a conductive liquid (an electrolyte). Lemon juice — citric acid — is a great electrolyte.\n\nStep 1: Roll each lemon firmly on the table to release the juice inside. Push a zinc nail into one end and a copper coin into a slit at the other end. Make sure the metals don't touch inside the lemon.\n\nStep 2: The zinc atoms dissolve into the acid, leaving electrons behind. Copper attracts those electrons. Connect a wire from the zinc nail of one lemon to the copper coin of the next, chaining your lemons in series.\n\nStep 3: Connect the free copper end and the free zinc end to your LED (long leg to copper). One lemon produces about 0.9 volts; a red LED needs roughly 1.8-2 volts, so two to four lemons in series will light it dimly. Dim the room lights to see it glow.\n\nThis is exactly how Alessandro Volta built the first battery in 1800 — he used zinc, copper, and salt-water-soaked cloth. Modern lithium-ion batteries use the same principle with different chemistry: electrons flowing from one material to another through your device.",
        "external_url": "https://www.sciencebuddies.org/stem-activities/lemon-battery",
        "external_label": "Science Buddies",
    },
    {
        "title": "Red Cabbage pH Indicator",
        "type": "experiment",
        "subject": "Science",
        "age_groups": ["16-18"],
        "difficulty": "Medium",
        "duration": "60 min",
        "materials": ["Half a red cabbage", "Boiling water", "Clear cups", "Household liquids to test (vinegar, lemon juice, baking soda solution, soap, milk)"],
        "summary": "Red cabbage contains anthocyanin, a pigment that changes color with pH — brew it into a rainbow-making acid-base indicator.",
        "body": "Chemists measure acidity with the pH scale from 0 (strong acid) to 14 (strong base), with 7 as neutral. Red cabbage contains anthocyanin, a pigment molecule whose structure — and therefore color — changes with the concentration of hydrogen ions around it.\n\nStep 1 — Brew the indicator: Chop the cabbage, cover it with boiling water, and let it steep for 15 minutes. Strain off the deep purple liquid. That's your indicator.\n\nStep 2 — Test: Pour a little indicator into several clear cups. Add a spoonful of each household liquid to its own cup and watch the colors shift: strong acids like lemon juice turn it red, weak acids like vinegar turn it pink, neutral liquids stay purple, weak bases like baking soda turn it blue-green, and strong bases like laundry soap push it toward yellow-green.\n\nStep 3 — Rank: Arrange your cups from red to green and you have built a working pH scale from kitchen supplies.\n\nGoing further: try 'titrating' — add vinegar drop by drop to a baking soda cup and watch the color walk back through the scale as the base is neutralized. This is the same principle labs use for quality control in food, water treatment, and medicine.",
        "external_url": "https://edu.rsc.org/experiments",
        "external_label": "Royal Society of Chemistry",
    },
    {
        "title": "Projectile Motion Challenge",
        "type": "problem",
        "subject": "Science",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Hard",
        "topic": "Physics — Kinematics",
        "summary": "A ball is kicked at 20 m/s at a 30° angle. How far does it travel before landing? Break the motion into horizontal and vertical parts to find out.",
        "body": "A footballer kicks a ball from ground level with an initial speed of 20 m/s at an angle of 30° above the horizontal. Ignoring air resistance and taking g = 9.8 m/s², answer:\n\n(a) How long is the ball in the air?\n(b) How far away does it land (its range)?\n(c) What is its maximum height?\n\nHint: Projectile motion splits into two independent motions. Horizontally, velocity is constant: vₓ = v·cos(θ). Vertically, the ball decelerates under gravity: v_y = v·sin(θ) − gt. Solve the vertical motion for the flight time, then use it in the horizontal motion.",
        "solution": "Components: vₓ = 20·cos30° ≈ 17.32 m/s, v_y = 20·sin30° = 10 m/s.\n\n(a) Time to peak: t = v_y/g = 10/9.8 ≈ 1.02 s. Total flight time = 2 × 1.02 ≈ 2.04 s.\n\n(b) Range = vₓ × t = 17.32 × 2.04 ≈ 35.3 m.\n\n(c) Max height = v_y²/(2g) = 100/19.6 ≈ 5.1 m.\n\nCheck with the range formula R = v²·sin(2θ)/g = 400 × sin60°/9.8 ≈ 35.3 m ✓",
        "external_url": "https://www.khanacademy.org/science/physics",
        "external_label": "Khan Academy Physics",
    },
    # ------------------ TECHNOLOGY ------------------
    {
        "title": "How the Internet Actually Works",
        "type": "article",
        "subject": "Technology",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Medium",
        "read_time": "8 min",
        "summary": "When you load a website, your request hops across routers, undersea cables and data centers in milliseconds. Here's the journey of a single click.",
        "body": "The internet is not a cloud — it's a physical network of fiber-optic cables (including about 1.4 million kilometers running under the oceans), routers, and data centers, all speaking a shared language called TCP/IP.\n\nWhen you type a website address, your computer first asks a DNS server — the internet's phone book — to translate the human-friendly name into an IP address, a numeric label like 142.250.72.14 that identifies the destination server.\n\nYour request is then chopped into small packets, each stamped with the destination address. Packets travel independently, hopping from router to router; each router reads the address and forwards the packet one step closer, like a global relay race. Packets from the same message may take completely different routes and still arrive correctly, because TCP numbers them and reassembles them in order, re-requesting any that got lost.\n\nThe destination server receives your request, builds a response — the web page — and streams it back to you the same way. The whole round trip usually takes under 100 milliseconds.\n\nThis packet-switching design, invented in the 1960s, is why the internet is so resilient: there is no central switchboard to break. If a cable is cut, routers simply route around the damage.",
        "external_url": "https://www.cloudflare.com/learning/network-layer/how-does-the-internet-work/",
        "external_label": "Cloudflare Learning Center",
    },
    {
        "title": "Machine Learning: How Computers Learn From Data",
        "type": "article",
        "subject": "Technology",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Hard",
        "read_time": "10 min",
        "summary": "Instead of following hand-written rules, machine learning systems find patterns in examples — the same way you learned to recognize cats without ever reading a definition of one.",
        "body": "Traditional software follows rules a programmer wrote: 'if temperature > 30, show sun icon'. Machine learning flips this: you give the computer thousands of examples with answers, and it works out the rules itself.\n\nConsider spam filtering. Rather than writing rules for every scam, engineers feed a model millions of emails labeled 'spam' or 'not spam'. The model starts with random guesses, measures how wrong it is (its 'loss'), and adjusts its internal numbers slightly to be less wrong — millions of times. This adjustment process, gradient descent, is the engine of nearly all modern AI.\n\nThere are three broad flavors. Supervised learning learns from labeled examples (spam detection, medical image diagnosis). Unsupervised learning finds hidden structure in unlabeled data (grouping customers by behavior). Reinforcement learning learns by trial and error with rewards (game-playing AIs, robot control).\n\nDeep learning stacks simple mathematical units — 'neurons' — into layered networks. Each layer detects increasingly abstract patterns: edges, then shapes, then faces. Large language models apply the same idea to text, learning from billions of sentences to predict the next word.\n\nThe critical caveat: models learn whatever is in their data, including its biases and gaps. A model trained on biased hiring data will make biased hiring predictions. That's why data quality and evaluation are as important as the algorithms themselves.",
        "external_url": "https://www.ibm.com/topics/machine-learning",
        "external_label": "IBM Technology Explainers",
    },
    {
        "title": "Build Your First Web Page in 30 Minutes",
        "type": "experiment",
        "subject": "Technology",
        "age_groups": ["all"],
        "difficulty": "Easy",
        "duration": "30 min",
        "materials": ["Any computer", "A text editor (Notepad or VS Code)", "A web browser"],
        "summary": "Write real HTML and CSS, save one file, and open your own web page in a browser — no installs, no frameworks, just the raw web.",
        "body": "Every website you've ever visited is built on HTML. You can create one right now.\n\nStep 1: Open a plain text editor and type:\n\n<!DOCTYPE html>\n<html>\n<head>\n  <title>My First Page</title>\n  <style>\n    body { font-family: sans-serif; background: #0f172a; color: #f1f5f9; padding: 40px; }\n    h1 { color: #34d399; }\n    .card { background: #1e293b; padding: 20px; border-radius: 12px; max-width: 400px; }\n  </style>\n</head>\n<body>\n  <h1>Hello, world!</h1>\n  <div class=\"card\">\n    <p>I built this page myself with HTML and CSS.</p>\n  </div>\n</body>\n</html>\n\nStep 2: Save the file as index.html (make sure it's not index.html.txt).\n\nStep 3: Double-click the file — it opens in your browser as a real web page.\n\nStep 4 — Experiment: change the colors, add an <img> tag with a picture URL, add more paragraphs, or an <a href=\"...\"> link. Every change you save appears when you refresh.\n\nWhat you just did — structure with HTML, styling with CSS — is the exact foundation professional developers use. Frameworks like React just generate this same HTML for you.",
        "external_url": "https://developer.mozilla.org/en-US/docs/Learn_web_development",
        "external_label": "MDN Web Docs",
    },
    {
        "title": "Binary Numbers Challenge",
        "type": "problem",
        "subject": "Technology",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Medium",
        "topic": "Computer Science — Number Systems",
        "summary": "Computers count with only two digits: 0 and 1. Can you translate between binary and decimal, and figure out why 'there are 10 kinds of people in the world'?",
        "body": "Binary is base-2: each digit position is worth a power of 2 (…, 16, 8, 4, 2, 1) instead of a power of 10.\n\nSo binary 1011 = (1×8) + (0×4) + (1×2) + (1×1) = 11 in decimal.\n\nYour challenges:\n(a) Convert binary 110101 to decimal.\n(b) Convert decimal 45 to binary.\n(c) What is binary 1011 + binary 110? Give the answer in binary.\n(d) A classic programmer joke says: 'There are 10 kinds of people in the world — those who understand binary and those who don't.' Explain the joke.",
        "solution": "(a) 110101 = 32+16+0+4+0+1 = 53.\n\n(b) 45 = 32+8+4+1 → 101101.\n\n(c) 1011 (11) + 110 (6) = 17 = 10001 in binary.\n\n(d) '10' read in binary is the number 2 — so the sentence really says 'there are two kinds of people'.",
        "external_url": "https://www.khanacademy.org/computing/computer-science",
        "external_label": "Khan Academy Computer Science",
    },
    # ------------------ ENGINEERING ------------------
    {
        "title": "Why Bridges Don't Fall Down",
        "type": "article",
        "subject": "Engineering",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Medium",
        "read_time": "7 min",
        "summary": "Every bridge is a battle between two invisible forces: tension pulling apart and compression squeezing together. Engineers win by choosing shapes that channel these forces safely into the ground.",
        "body": "Stand on a plank between two chairs and it sags: the top of the plank squeezes together (compression) while the bottom stretches apart (tension). Every structure on Earth manages these same two forces.\n\nBeam bridges — the simplest type — work fine for short spans, but sag more as they get longer. To span farther, engineers change the geometry.\n\nArch bridges convert the deck's weight into pure compression that flows down the curve into massive supports called abutments. Stone is weak in tension but incredibly strong in compression, which is why Roman arch bridges still stand after 2,000 years.\n\nTruss bridges use networks of triangles. A triangle is the only shape that cannot change form without changing the length of a side — push on a square and it becomes a diamond; push on a triangle and it pushes back. Each triangle member carries clean tension or compression.\n\nSuspension bridges, like the Golden Gate, flip the problem: the deck hangs from vertical cables attached to enormous main cables draped between towers. The cables work entirely in tension — and steel cable is the strongest tension material we mass-produce. That's how spans over 1.5 km become possible.\n\nEngineers then add safety factors, designing every part to survive several times the biggest load it should ever see — because wind, earthquakes, and resonance (marching soldiers have collapsed bridges!) don't read blueprints.",
        "external_url": "https://www.teachengineering.org/",
        "external_label": "TeachEngineering",
    },
    {
        "title": "How Rockets Work: Newton's Third Law in Action",
        "type": "article",
        "subject": "Engineering",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Hard",
        "read_time": "8 min",
        "summary": "Rockets don't push against air — they throw mass out the back extremely fast. Newton's third law and the rocket equation explain both the power and the brutal cost of spaceflight.",
        "body": "A rocket engine is a machine for throwing mass. Burn fuel with oxidizer in a chamber, and the hot gas blasts out of the nozzle at up to 4.5 km/s. By Newton's third law — every action has an equal and opposite reaction — the rocket is pushed the other way. No air is needed; rockets work better in vacuum.\n\nThe catch is captured by the Tsiolkovsky rocket equation: Δv = vₑ·ln(m₀/m₁). The speed you can gain (Δv) depends on your exhaust velocity and the ratio of your full mass to your empty mass — logarithmically. Reaching orbit requires about 9.4 km/s of Δv, and the logarithm is merciless: a typical orbital rocket must be roughly 90% propellant by mass. The Saturn V weighed 2,900 tonnes; the Apollo capsule that came home weighed under 6.\n\nStaging fights the equation: dropping empty tanks and engines mid-flight sheds dead weight, resetting the mass ratio. Reusability, mastered in the 2010s with propulsively-landing boosters, fights the economics instead — the hardware is the expensive part, so flying it many times cuts the cost per launch dramatically.\n\nEngineering a rocket is a chain of controlled extremes: turbopumps moving a swimming pool of propellant per minute, combustion at 3,300°C beside plumbing at −180°C, and guidance computers correcting the flight path dozens of times per second.",
        "external_url": "https://www.grc.nasa.gov/www/k-12/rocket/",
        "external_label": "NASA Glenn Research Center",
    },
    {
        "title": "The Spaghetti Tower Challenge",
        "type": "experiment",
        "subject": "Engineering",
        "age_groups": ["13-15"],
        "difficulty": "Easy",
        "duration": "45 min",
        "materials": ["20 sticks of dry spaghetti", "1 meter of tape", "1 meter of string", "1 marshmallow", "Scissors", "A timer"],
        "summary": "The famous design challenge used in engineering schools worldwide: build the tallest tower that holds a marshmallow on top, using only spaghetti, tape and string.",
        "body": "Your mission: in 18 minutes, build the tallest free-standing structure that supports one whole marshmallow on top, using only 20 spaghetti sticks, tape and string.\n\nWhy it's harder than it looks: the marshmallow seems light, but spaghetti is brittle and buckles suddenly under compression. Most first attempts collapse in the final seconds when the marshmallow goes on.\n\nEngineering strategy:\n1. Prototype early — put the marshmallow on top of a small structure first, then grow it. Teams that 'save the marshmallow for the end' usually fail.\n2. Use triangles — a triangle cannot deform without breaking a side. Structures built from tetrahedra (3-sided pyramids) are dramatically stronger than squares.\n3. Wide base, light top — like the Eiffel Tower, put most material near the ground.\n4. Bundle spaghetti — two or three sticks taped together resist buckling far better than one.\n\nInterestingly, in studies of this challenge, kindergartners often beat business students: they prototype immediately and iterate, while adults spend their time planning a single 'perfect' design. That lesson — build, test, improve — is the actual engineering design process.\n\nMeasure your tower from table to marshmallow base. The world-class score is over 60 cm. Can you beat it?",
        "external_url": "https://www.sciencebuddies.org/stem-activities",
        "external_label": "Science Buddies STEM Activities",
    },
    {
        "title": "Egg Drop Lander Design",
        "type": "experiment",
        "subject": "Engineering",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Medium",
        "duration": "90 min",
        "materials": ["1 raw egg", "Straws", "Cotton balls", "Paper", "Tape", "Plastic bag (parachute)", "String", "Scissors"],
        "summary": "Design a lander that protects a raw egg from a 3-meter drop — the same crumple-zone and parachute physics NASA uses to land rovers on Mars.",
        "body": "When your egg hits the ground, its momentum must go to zero. Physics gives you one lever: F = Δp/Δt. You can't change the momentum, but if you stretch the impact time, the force shrinks proportionally. Every safety technology — car crumple zones, airbags, bike helmets, Mars landing systems — is a way of buying more milliseconds.\n\nDesign approaches:\n1. Crumple zone: build a straw lattice around the egg that collapses progressively on impact, absorbing energy as it fails. Sacrificial structure is good structure.\n2. Cushioning: cotton balls directly around the egg spread the force over more area and time.\n3. Parachute: a plastic bag canopy increases air resistance, lowering impact velocity in the first place. Drag scales with canopy area.\n4. Orientation control: a badminton-shuttlecock shape guarantees your strongest side hits first.\n\nBuild rules: the egg must be raw, the lander must free-fall (no guiding), and after the drop the egg must be crack-free.\n\nTest from 1 m, then 2 m, then 3 m. After each failure, do a real engineer's post-mortem: where did the energy go? Which part failed first? Iterate. NASA's Curiosity rover team ran thousands of such simulations before the real '7 minutes of terror' descent — your 3 meters is their 125 million kilometers.",
        "external_url": "https://www.sciencebuddies.org/stem-activities/egg-drop",
        "external_label": "Science Buddies",
    },
    {
        "title": "Gear Ratio Puzzle",
        "type": "problem",
        "subject": "Engineering",
        "age_groups": ["16-18"],
        "difficulty": "Medium",
        "topic": "Mechanical Engineering — Gears",
        "summary": "A 12-tooth gear drives a 36-tooth gear. Work out the speed, torque, and direction of the output — the trade-off at the heart of every bicycle and gearbox.",
        "body": "A small gear (the driver) with 12 teeth is meshed with a large gear (the driven) with 36 teeth. The driver spins clockwise at 300 RPM with a torque of 2 N·m.\n\n(a) What is the gear ratio?\n(b) How fast does the large gear turn, and in which direction?\n(c) What torque does the large gear deliver (assume no friction losses)?\n(d) A cyclist shifts to a larger rear cog when climbing a hill. Using your answers, explain why.",
        "solution": "(a) Gear ratio = driven teeth / driver teeth = 36/12 = 3:1.\n\n(b) The driven gear turns 3× slower: 300/3 = 100 RPM, counterclockwise (meshed external gears reverse direction).\n\n(c) Torque multiplies by the same ratio: 2 × 3 = 6 N·m. Power (speed × torque) is conserved — you trade speed for force.\n\n(d) A larger rear cog increases the ratio between pedal and wheel, so each pedal stroke delivers more torque to the wheel at lower speed — exactly what you need against gravity on a climb.",
        "external_url": "https://www.teachengineering.org/",
        "external_label": "TeachEngineering",
    },
    # ------------------ ARTS ------------------
    {
        "title": "Color Theory: The Science of What Looks Good",
        "type": "article",
        "subject": "Arts",
        "age_groups": ["all"],
        "difficulty": "Easy",
        "read_time": "6 min",
        "summary": "Why do some color combinations feel electric and others feel muddy? The color wheel, contrast and harmony rules give designers a repeatable system for beauty.",
        "body": "In 1666, Isaac Newton bent sunlight through a prism, split it into a spectrum, and joined the ends into the first color wheel. Artists have navigated by it ever since.\n\nThe traditional wheel starts with three primary colors — red, yellow, blue — which mix into secondary colors (orange, green, purple) and then tertiary blends. From this geometry come the classic harmony rules:\n\nComplementary colors sit opposite each other (blue/orange, red/green). Placed together they create maximum vibrance — which is why movie posters are saturated in teal and orange, and why sports teams love these pairs.\n\nAnalogous colors are neighbors (blue, teal, green). They feel calm and cohesive, like a forest or an ocean. Most 'aesthetic' Instagram feeds are analogous palettes.\n\nTriadic schemes pick three colors evenly spaced on the wheel — bold but balanced, beloved by comic book artists.\n\nBeyond hue, designers control saturation (intensity) and value (lightness). A reliable professional trick: build your design in shades of one hue, then add a single saturated accent color for the important elements. Your eye goes exactly where the designer wants.\n\nColor also carries temperature and emotion: warm colors (red, orange) advance toward the viewer and energize; cool colors (blue, green) recede and calm. Restaurants paint in red because it stimulates appetite; hospitals paint in blue-green because it lowers heart rate. Once you learn the rules, you see them engineered everywhere.",
        "external_url": "https://www.canva.com/colors/color-wheel/",
        "external_label": "Canva Color Wheel",
    },
    {
        "title": "The Golden Ratio in Art and Nature",
        "type": "article",
        "subject": "Arts",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Medium",
        "read_time": "7 min",
        "summary": "One irrational number — 1.618… — appears in sunflowers, seashells, the Parthenon and Renaissance paintings. Coincidence, mathematics, or myth? A bit of all three.",
        "body": "Divide a line so that the whole relates to the long part exactly as the long part relates to the short part, and you get the golden ratio: φ = (1+√5)/2 ≈ 1.618. The Greeks considered this proportion uniquely pleasing.\n\nThe ratio is deeply connected to the Fibonacci sequence (1, 1, 2, 3, 5, 8, 13...): divide each Fibonacci number by the previous one and the results converge to φ. This is why golden spirals and Fibonacci spirals look nearly identical.\n\nIn nature the connection is real and mathematical. Sunflower seeds pack in spirals counting 34 one way, 55 the other — consecutive Fibonacci numbers — because placing each new seed a 'golden angle' (about 137.5°) from the last packs seeds most efficiently. Pinecones, pineapples and many succulents follow the same rule.\n\nIn art, the story is partly myth. Claims that the Parthenon or the pyramids were designed on φ are unsupported by their measurements. But some artists did use it deliberately: Salvador Dalí built 'The Sacrament of the Last Supper' inside a golden rectangle with a dodecahedron overhead, and Le Corbusier based his Modulor architecture system on it.\n\nWhether or not φ is 'the most beautiful number,' it remains a powerful composition tool: golden-rectangle grids and the related rule of thirds help artists place focal points off-center, where the eye finds them most naturally. Try analyzing your favorite photo — you may find the horizon and subject fall near golden lines.",
        "external_url": "https://www.mathsisfun.com/numbers/golden-ratio.html",
        "external_label": "Math is Fun",
    },
    {
        "title": "Stop-Motion Animation With Your Phone",
        "type": "experiment",
        "subject": "Arts",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Easy",
        "duration": "90 min",
        "materials": ["Smartphone", "Free stop-motion app (Stop Motion Studio)", "Modeling clay or LEGO figures", "Desk lamp", "Books to prop the phone"],
        "summary": "Make objects come alive using the same frame-by-frame technique behind Wallace & Gromit and the earliest movie special effects.",
        "body": "Film is an illusion: show 12 or more still images per second and the human brain fuses them into motion. Stop-motion exploits this directly — you photograph an object, nudge it slightly, photograph again, and repeat.\n\nStep 1 — Stabilize: prop your phone firmly between books or on a tripod. Even a millimeter of camera drift between frames makes footage look shaky.\n\nStep 2 — Light: close the curtains and use a desk lamp. Sunlight changes minute to minute and causes distracting flicker across frames.\n\nStep 3 — Animate: open a stop-motion app and photograph your character. Move it about 5 mm, shoot again. For walking, move the legs alternately; for a jump, exaggerate a crouch before liftoff — animators call this 'anticipation' and it makes motion feel alive.\n\nStep 4 — Timing: at 12 frames per second, a 10-second scene needs 120 photos. Slow, smooth actions need small moves; fast actions need bigger jumps between frames.\n\nStep 5 — Polish: add a title card, sound effects and music in the app.\n\nThe pros work exactly the same way — the movie 'Coraline' was shot at 24 frames per second, and its animators produced only a few seconds of final footage per day. Start with a 5-second scene: a clay ball that rolls, squashes and jumps teaches you 80% of the craft.",
        "external_url": "https://www.adobe.com/creativecloud/animation/discover/stop-motion-animation.html",
        "external_label": "Adobe Creative Cloud",
    },
    {
        "title": "One-Point Perspective Drawing Challenge",
        "type": "problem",
        "subject": "Arts",
        "age_groups": ["13-15"],
        "difficulty": "Easy",
        "topic": "Drawing — Perspective",
        "summary": "Draw a 3D city street on flat paper using one vanishing point — the Renaissance trick that changed art forever.",
        "body": "Before the 1400s, paintings looked flat. Then Filippo Brunelleschi demonstrated linear perspective: parallel lines going away from you appear to meet at a single 'vanishing point' on the horizon. Suddenly painters could build convincing 3D space on a flat surface.\n\nYour challenge: draw a city street in one-point perspective.\n\n1. Draw a horizontal line across your page — the horizon (eye level).\n2. Mark one dot in the middle: the vanishing point (VP).\n3. Draw two lines from the bottom corners of your page to the VP — this is your road.\n4. Buildings: draw a vertical line for the front corner of a building, then connect its top and bottom to the VP. Close it off with vertical and horizontal edges. Every 'depth' edge must aim at the VP; every vertical stays vertical.\n5. Add windows, doors, lane markings and a sidewalk — all depth lines still obey the VP.\n\nCheckpoint: hold a ruler along any receding edge in your drawing. If it doesn't pass through the VP, that's the line breaking the illusion.",
        "solution": "Success criteria: (1) horizon line with a single VP; (2) all receding edges converge exactly on the VP; (3) verticals perpendicular to the horizon; (4) objects shrink and spacing compresses as they approach the VP. Common fix: window rows on side walls must also converge to the VP, not stay parallel — that is the #1 beginner mistake.",
        "external_url": "https://www.studentartguide.com/articles/one-point-perspective-drawing",
        "external_label": "Student Art Guide",
    },
    # ------------------ MATHEMATICS ------------------
    {
        "title": "Fibonacci and the Hidden Math of Nature",
        "type": "article",
        "subject": "Mathematics",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Easy",
        "read_time": "6 min",
        "summary": "Start with 1, 1 and keep adding the last two numbers — this simple rule generates a sequence that nature uses to build sunflowers, pinecones and spiral galaxies.",
        "body": "In 1202, Leonardo of Pisa — nicknamed Fibonacci — posed a puzzle about breeding rabbits, and the answer produced the sequence 1, 1, 2, 3, 5, 8, 13, 21, 34, 55… Each number is the sum of the two before it.\n\nEight centuries later, this sequence keeps showing up in nature. Count the petals on many flowers: lilies have 3, buttercups 5, delphiniums 8, some daisies 34 or 55. Count the spirals on a pinecone or pineapple: you'll typically find consecutive Fibonacci numbers winding in opposite directions.\n\nWhy? When a plant grows new seeds or leaves from its center, the most efficient strategy is to place each one at a fixed angle from the previous — about 137.5°, the 'golden angle'. This packs elements with no wasted space and no stacking, and the spiral counts that emerge from this angle are Fibonacci numbers. It's not magic; it's optimization, run by evolution.\n\nThe sequence also hides a famous constant: divide any Fibonacci number by the one before it (55/34 ≈ 1.6176…) and the ratios approach the golden ratio φ ≈ 1.618.\n\nTry it yourself: find a pinecone and count its clockwise and counterclockwise spirals, or check the leaf arrangement on a succulent. You'll be reading the same mathematics that structures galaxies and hurricanes — patterns that emerge whenever growth and geometry negotiate for space.",
        "external_url": "https://www.mathsisfun.com/numbers/fibonacci-sequence.html",
        "external_label": "Math is Fun",
    },
    {
        "title": "What Calculus Actually Measures",
        "type": "article",
        "subject": "Mathematics",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Hard",
        "read_time": "9 min",
        "summary": "Calculus is not about memorizing rules — it's two big ideas: zooming in until curves look straight (derivatives), and adding up infinitely many tiny pieces (integrals).",
        "body": "Your speedometer performs calculus every moment. Speed is distance divided by time — but at a single instant, no time passes and no distance is covered. So what is 'speed right now'?\n\nNewton and Leibniz answered in the 1660s-70s: measure the average speed over a shrinking window — one second, a millisecond, a microsecond — and watch what value those averages approach. That limiting value is the derivative: the instantaneous rate of change. Geometrically, it's the slope of a curve at a point; zoom into any smooth curve far enough and it looks like a straight line whose slope you can read off.\n\nThe second idea runs the other way. To find the area under a curve — say, total distance from a changing speed graph — slice it into thin rectangles, sum them, and let the slices become infinitely thin. That limit is the integral.\n\nThe stunning result connecting them is the Fundamental Theorem of Calculus: differentiation and integration are inverse operations. The area-so-far under a curve grows at exactly the rate given by the curve itself.\n\nThis machinery is why calculus underlies nearly all quantitative science: planetary orbits (rates of change of position), drug dosing (accumulation and decay in the bloodstream), machine learning (gradient descent literally follows derivatives downhill), and epidemiology (how fast infections grow). When you learn the rules — power rule, chain rule — you're learning shortcuts for the zoom-and-sum reasoning underneath. Keep the ideas in view and the rules stop being arbitrary.",
        "external_url": "https://www.khanacademy.org/math/calculus-1",
        "external_label": "Khan Academy Calculus",
    },
    {
        "title": "Probability: Why the House Always Wins",
        "type": "article",
        "subject": "Mathematics",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Medium",
        "read_time": "7 min",
        "summary": "Casinos don't gamble — they apply the law of large numbers. Expected value explains why small edges, repeated thousands of times, become certainties.",
        "body": "Every casino game is a machine built on one concept: expected value (EV) — the average outcome per play if you played infinitely many times.\n\nTake European roulette. Bet $1 on red: 18 red pockets win, 18 black lose, and 1 green zero also loses. Your EV = (18/37)(+$1) + (19/37)(−$1) = −$0.027. You lose about 2.7 cents per dollar bet — on average.\n\nIn one evening, anything can happen; that's variance, and it's what makes gambling feel winnable. But the law of large numbers guarantees that as the number of bets grows, the actual average converges to the expected value. A single player might beat the odds; a million players collectively cannot. The casino doesn't need luck — it needs volume.\n\nThe same mathematics runs the legitimate economy. Insurance companies are 'casinos in reverse': they charge premiums slightly above the expected payout of claims, profitable across millions of policies even though any single house fire is unpredictable. Index-fund investing exploits positive expected value plus time. Airlines overbook seats based on the expected number of no-shows.\n\nThe practical lesson: judge decisions by their expected value and variance, not by individual outcomes. A good decision can have a bad outcome and vice versa — but over a lifetime of decisions, the averages win. That mental habit, more than any formula, is what probability theory teaches.",
        "external_url": "https://www.mathsisfun.com/data/probability.html",
        "external_label": "Math is Fun",
    },
    {
        "title": "Measure a Building's Height With Trigonometry",
        "type": "experiment",
        "subject": "Mathematics",
        "age_groups": ["16-18"],
        "difficulty": "Medium",
        "duration": "45 min",
        "materials": ["Protractor", "Drinking straw", "Tape", "String and small weight (washer or nut)", "Tape measure", "Calculator"],
        "summary": "Build a clinometer from a protractor and use the tangent function to measure the height of your school, a tree, or any building — no ladder required.",
        "body": "Surveyors have measured mountains this way for centuries: if you know how far you are from an object and the angle up to its top, trigonometry hands you the height.\n\nStep 1 — Build a clinometer: tape the straw along the flat edge of the protractor. Tie the weighted string to the center hole so it hangs freely across the scale.\n\nStep 2 — Sight: stand a measured distance from the building (try 20 m) and look through the straw at the very top. Gravity keeps the string vertical, so a partner can read the angle the string crosses. If the string reads 40° from the 90° mark, your elevation angle is 40°.\n\nStep 3 — Compute: the tangent of your angle equals opposite over adjacent — height above your eye divided by distance. So height = distance × tan(angle). With 20 m and 40°: 20 × tan 40° ≈ 20 × 0.839 ≈ 16.8 m. Add your own eye height (~1.5 m) for the total: about 18.3 m.\n\nStep 4 — Validate: repeat from a different distance. If both calculations agree within a meter, your measurement is solid — that cross-check is exactly how real surveyors verify results.\n\nExtension: measure a tree, a flagpole and a lamppost, then estimate the error introduced by ±2° of angle reading. You'll discover why surveying instruments obsess over angular precision.",
        "external_url": "https://www.mathsisfun.com/algebra/trigonometry.html",
        "external_label": "Math is Fun — Trigonometry",
    },
    {
        "title": "The Locker Problem",
        "type": "problem",
        "subject": "Mathematics",
        "age_groups": ["13-15", "16-18"],
        "difficulty": "Medium",
        "topic": "Number Theory — Factors",
        "summary": "1000 lockers, 1000 students, a beautiful pattern: after everyone walks the hallway, which lockers remain open? The answer hides in square numbers.",
        "body": "A school hallway has 1000 closed lockers. Student 1 walks by and opens every locker. Student 2 closes every 2nd locker (2, 4, 6…). Student 3 changes every 3rd locker — closing open ones, opening closed ones. This continues: student n toggles every nth locker, all the way to student 1000.\n\nQuestion: after all 1000 students pass, which lockers are open?\n\nHints:\n- Track locker 12: it gets toggled by students 1, 2, 3, 4, 6, 12 — its factors. Six toggles: it ends closed.\n- Track locker 16: toggled by students 1, 2, 4, 8, 16 — five toggles: it ends open.\n- What's mathematically special about numbers with an odd number of factors?",
        "solution": "A locker ends open if it is toggled an odd number of times — i.e., if it has an odd number of factors. Factors normally come in pairs (for 12: 1×12, 2×6, 3×4). The only numbers with an unpaired factor are perfect squares (16 = 4×4 — the 4 pairs with itself).\n\nSo the open lockers are the perfect squares: 1, 4, 9, 16, 25, …, 961. Since 31² = 961 ≤ 1000 < 32² = 1024, exactly 31 lockers remain open.",
        "external_url": "https://nrich.maths.org/",
        "external_label": "NRICH (University of Cambridge)",
    },
    {
        "title": "The Fence Optimization Problem",
        "type": "problem",
        "subject": "Mathematics",
        "age_groups": ["18+"],
        "difficulty": "Hard",
        "topic": "Calculus — Optimization",
        "summary": "You have 100 m of fence and a river. What rectangle encloses the most grazing area? Set up the function, take the derivative, and let calculus find the answer.",
        "body": "A farmer has 100 meters of fencing and wants to enclose a rectangular field along a straight river. The river side needs no fence.\n\n(a) Express the enclosed area A as a function of one variable.\n(b) Find the dimensions that maximize the area, and prove it's a maximum.\n(c) The classic isoperimetric result says a square is optimal for a fully-fenced rectangle. Why is the answer here not a square?\n\nSetup hint: call the two sides perpendicular to the river x each. The side parallel to the river is then 100 − 2x, so A(x) = x(100 − 2x).",
        "solution": "(a) A(x) = x(100 − 2x) = 100x − 2x², for 0 < x < 50.\n\n(b) A′(x) = 100 − 4x = 0 → x = 25. A″(x) = −4 < 0, confirming a maximum. Dimensions: 25 m × 50 m, area = 1250 m².\n\n(c) The river replaces one side for free, changing the constraint. The optimum uses the free side maximally: the parallel side (50 m) is twice the perpendicular sides (25 m). With all four sides fenced, the same method yields the 25×25 square (625 m²) — half the area, which shows how much the river is worth.",
        "external_url": "https://www.khanacademy.org/math/calculus-1",
        "external_label": "Khan Academy Calculus",
    },
    {
        "title": "The Birthday Paradox",
        "type": "problem",
        "subject": "Mathematics",
        "age_groups": ["16-18", "18+"],
        "difficulty": "Medium",
        "topic": "Probability",
        "summary": "In a class of just 23 people, there's a 50% chance two share a birthday. Prove this counterintuitive result — then see why it matters for computer security.",
        "body": "How many people must be in a room before it's more likely than not that two share a birthday? Intuition says somewhere near 183 (half of 365). The real answer is 23.\n\n(a) Explain why it's easier to compute the probability that NO two people share a birthday.\n(b) Write the formula for that probability with n people (assume 365 equally likely birthdays).\n(c) Verify that at n = 23 the no-match probability drops below 50%.\n(d) Bonus: this 'paradox' is the basis of the birthday attack in cryptography. Why do hash collisions appear after roughly √N random attempts instead of N?",
        "solution": "(a) 'At least one match' has many overlapping cases; its complement — all birthdays distinct — is one clean product.\n\n(b) P(no match) = 365/365 × 364/365 × 363/365 × … × (365−n+1)/365.\n\n(c) For n = 23 the product ≈ 0.4927, so P(at least one match) ≈ 50.7%.\n\n(d) With n people there are n(n−1)/2 ≈ n²/2 pairs — comparisons grow quadratically. Matches become likely when n²/2 ≈ N, i.e., n ≈ √(2N). For a hash space of N outputs, collisions appear after ~√N attempts — which is why a 128-bit hash offers only ~64 bits of collision resistance.",
        "external_url": "https://www.mathsisfun.com/data/probability-shared-birthday.html",
        "external_label": "Math is Fun",
    },
]

DEMO_IDEAS = [
    {
        "title": "Solar-Powered Phone Charging Station for School",
        "description": "Build a bench in the schoolyard with a solar panel roof and USB ports so students can charge devices with clean energy. We could track energy generated on a display and use the data in physics class to study efficiency across seasons.",
        "category": "Engineering",
    },
    {
        "title": "AI Study Buddy That Quizzes You From Your Notes",
        "description": "An app where you photograph your class notes and it generates practice questions from them. It would use spaced repetition to re-ask the questions you got wrong right before you're about to forget them.",
        "category": "Technology",
    },
    {
        "title": "Fibonacci Garden Art Installation",
        "description": "Plant a school garden where flower beds follow the Fibonacci spiral, with plaques explaining the math. It's art, math, and biology in one project — and a great photo spot to get more students interested in the pattern.",
        "category": "Arts",
    },
    {
        "title": "Water Quality Testing of the Local Creek",
        "description": "A monthly citizen-science project: measure pH, turbidity and nitrates in the creek behind the sports field, publish the data openly, and alert the city if pollution spikes. Could partner with the chemistry lab for equipment.",
        "category": "Science",
    },
]
